/**
 * Client ID Generator Service
 * 
 * Generates unique, sequential clientIds for client records
 * Format: C000001, C000002, C000003, etc.
 * 
 * This service ensures:
 * - Server-side generation only (never client-provided)
 * - Sequential numbering for easy reference
 * - Bootstrap-safe (works when database is empty)
 * - Transactional support (works within MongoDB sessions)
 * - Immutability (clientId cannot be changed after creation)
 * - Race-condition safety via transaction isolation
 * - FIRM-SCOPED uniqueness (each firm starts with C000001)
 * 
 * IMPORTANT: No Counter collection is used - IDs are generated by querying
 * the latest document within the same transaction session.
 * 
 * FIRM SCOPING: Each firm has its own independent client ID sequence.
 * - FIRM001 gets C000001, C000002, C000003, ...
 * - FIRM002 gets C000001, C000002, C000003, ...
 * - This allows each firm to have their own client numbering system
 */

const Client = require('../models/Client.model');

/**
 * Generate the next available clientId within a transaction
 * Queries the latest client within the firm and increments, bootstrap-safe for empty collections
 * 
 * IMPORTANT: clientId is FIRM-SCOPED (unique within a firm)
 * - Each firm has its own sequence: FIRM001 gets C000001, FIRM002 gets C000001
 * - Client IDs are generated sequentially per firm
 * - This respects the compound unique index on (firmId, clientId)
 * 
 * @param {ObjectId} firmId - Firm ObjectId for firm-scoped ID generation (required)
 * @param {object} session - MongoDB session for transactional reads (required for atomicity)
 * @returns {Promise<string>} Next clientId in format C000001
 */
const generateNextClientId = async (firmId, session = null) => {
  if (!firmId) {
    throw new Error('firmId is required for clientId generation');
  }
  
  try {
    // Query the latest client WITHIN THIS FIRM within the transaction session
    // Sort by clientId descending to get the highest number in this firm
    // FIRM-SCOPED: Only look at clients within this firm
    const queryOptions = session ? { session } : {};
    const lastClient = await Client
      .findOne({ firmId, clientId: /^C\d+$/ }, {}, queryOptions)
      .sort({ clientId: -1 });
    
    // Bootstrap case: no clients exist yet for this firm
    if (!lastClient || !lastClient.clientId) {
      console.log(`[Client ID Generator] Bootstrap: Generated first clientId: C000001 for firm: ${firmId}`);
      return 'C000001';
    }
    
    // Extract the numeric portion from the last clientId (e.g., C000001 -> 1)
    const lastNumber = parseInt(lastClient.clientId.slice(1), 10);
    
    // Increment and format with leading zeros (6 digits)
    const nextNumber = lastNumber + 1;
    const clientId = `C${String(nextNumber).padStart(6, '0')}`;
    
    console.log(`[Client ID Generator] Generated clientId: ${clientId} for firm: ${firmId}`);
    
    return clientId;
  } catch (error) {
    console.error('[Client ID Generator] Error generating clientId:', error);
    throw new Error('Failed to generate clientId during firm provisioning');
  }
};

/**
 * Validate clientId format
 * @param {string} clientId - clientId to validate
 * @returns {boolean} True if valid format
 */
const validateClientIdFormat = (clientId) => {
  if (!clientId || typeof clientId !== 'string') {
    return false;
  }
  
  // Must match format: C followed by 6 digits
  return /^C\d{6}$/.test(clientId);
};

/**
 * Check if clientId already exists
 * @param {string} clientId - clientId to check
 * @returns {Promise<boolean>} True if clientId exists
 */
const clientIdExists = async (clientId) => {
  try {
    const client = await Client.findOne({ clientId }).lean();
    return !!client;
  } catch (error) {
    console.error('[Client ID Generator] Error checking clientId existence:', error);
    throw new Error('Failed to check clientId existence');
  }
};

module.exports = {
  generateNextClientId,
  validateClientIdFormat,
  clientIdExists,
};
