const NotificationTypes = Object.freeze({
  DOCKET_ASSIGNED: 'DOCKET_ASSIGNED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  DOCKET_REASSIGNED: 'DOCKET_REASSIGNED',
  DOCKET_ROUTED_TO_WORKBASKET: 'DOCKET_ROUTED_TO_WORKBASKET',
  QC_RETURNED: 'QC_RETURNED',
  PENDED_DOCKET_REOPENED: 'PENDED_DOCKET_REOPENED',
  CLIENT_UPLOAD: 'CLIENT_UPLOAD',
  SLA_BREACHED: 'SLA_BREACHED',
  DOCKET_DUE_SOON: 'DOCKET_DUE_SOON',
  DOCKET_OVERDUE: 'DOCKET_OVERDUE',
});

module.exports = {
  NotificationTypes,
};
