export const designTokens = {
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  typography: {
    pageTitle: '28px',
    sectionTitle: '18px',
    body: '14px',
    caption: '12px',
    semibold: 600,
    medium: 500,
  },
  colors: {
    primary: '#1E3A8A',
    accent: '#4F46E5',
    success: '#059669',
    warning: '#D97706',
    error: '#E11D48',
    slate900: '#0F172A',
    border: '#E5E7EB',
    textMain: '#111827',
    textMuted: '#6B7280',
  },
};

export const caseStatusAppearance = {
  WB: { label: 'WB', tone: 'neutral' },
  WL: { label: 'WL', tone: 'open' },
  ASSIGNED: { label: 'Assigned', tone: 'escalated' },
  IN_PROGRESS: { label: 'In Progress', tone: 'review' },
  PENDING: { label: 'Pended', tone: 'warning' },
  RESOLVED: { label: 'Resolved', tone: 'success' },
  FILED: { label: 'Filed', tone: 'dark' },
  DRAFT: { label: 'Draft', tone: 'draft' },
  OPEN: { label: 'Open', tone: 'open' },
  UNDER_REVIEW: { label: 'In Review', tone: 'review' },
  ESCALATED: { label: 'Escalated', tone: 'escalated' },
  CLOSED: { label: 'Closed', tone: 'closed' },
  UNASSIGNED: { label: 'Unassigned', tone: 'draft' },
  CREATED: { label: 'Created', tone: 'draft' },
  REVIEW: { label: 'Review', tone: 'review' },
  COMPLETED: { label: 'Completed', tone: 'success' },
  ARCHIVED: { label: 'Archived', tone: 'dark' },
};
