import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert';
const source = fs.readFileSync(path.resolve(process.cwd(), 'src/components/docket/GuidedDocketForm.jsx'), 'utf8');
assert.ok(source.includes('manualClassification'));
assert.ok(source.includes("if (name === 'categoryId' || name === 'subcategoryId') setManualClassification(true);"));
assert.ok(source.includes('const applySuggestion = () =>'));
assert.ok(source.includes('setSuggestion(null);'));
assert.ok(!source.includes("applySuggestion = () => {\n    if (!suggestion || manualClassification) return;\n    updateField('categoryId'"));
assert.ok(source.includes('Apply suggestion'));
console.log('docketCategorySuggestionManualSelection.test.mjs passed');
