import React, { useCallback, useEffect, useState } from 'react';
import { SuperAdminLayout } from '../components/common/SuperAdminLayout';
import { Card } from '../components/common/Card';
import { Button } from '../components/common/Button';
import { Loading } from '../components/common/Loading';
import { superadminService } from '../services/superadminService';

export const SuperadminFeatureFlagsPage = () => {
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [flags, setFlags] = useState([]);
  const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState(''); const [notes, setNotes] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const res = await superadminService.getFeatureFlags(); setFlags(res?.data?.flags || []); } catch (e) { setError(e?.response?.data?.message || 'Failed to load feature flags.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { if (!editing) return; setSaving(true); setSaveError(''); try { await superadminService.updateFeatureFlag(editing.key, { enabledGlobally: editing.enabledGlobally, rolloutStage: editing.rolloutStage, notes }); setEditing(null); setNotes(''); await load(); } catch (e) { setSaveError(e?.response?.data?.message || 'Failed to save feature flag'); } finally { setSaving(false); } };
  if (loading) return <SuperAdminLayout><Loading message="Loading feature flags..." /></SuperAdminLayout>;
  return <SuperAdminLayout><div className="mx-auto w-full max-w-7xl space-y-4"><h1 className="text-2xl font-semibold">Feature Flags</h1><p className="text-sm text-gray-500">Feature Flags controls platform rollout metadata only. It does not expose or modify client records, dockets, tasks, attachments, documents, or private client content.</p>{error ? <Card><p className="text-sm text-red-700">{error}</p><Button variant="secondary" onClick={load}>Retry</Button></Card> : null}<Card><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th>Key</th><th>Label</th><th>Description</th><th>Status</th><th>Scope</th><th>Rollout</th><th>Risk</th><th>Enabled firms</th><th>Updated</th><th /></tr></thead><tbody>{flags.map((f) => <tr key={f.key} className="border-t"><td>{f.key}</td><td>{f.label}</td><td>{f.description}</td><td>{f.status}</td><td>{f.scope}</td><td>{f.rolloutStage}</td><td>{f.riskLevel}</td><td>{f.enabledFirmCount}</td><td>{f.updatedAt || '—'}</td><td><Button variant="secondary" onClick={() => { setEditing({ ...f }); setSaveError(''); }}>Edit</Button></td></tr>)}</tbody></table></div>{!flags.length ? <p className="text-sm text-gray-600">No feature flags found.</p> : null}</Card>{editing ? <Card><h2 className="text-lg font-semibold">Edit {editing.key}</h2><div className="space-y-2"><label className="block"><span className="text-sm">Enabled globally</span><input type="checkbox" checked={Boolean(editing.enabledGlobally)} onChange={(e) => setEditing((prev) => ({ ...prev, enabledGlobally: e.target.checked }))} /></label><label className="block"><span className="text-sm">Rollout stage</span><select value={editing.rolloutStage} onChange={(e) => setEditing((prev) => ({ ...prev, rolloutStage: e.target.value }))} className="ml-2 rounded border px-2 py-1"><option value="off">off</option><option value="internal">internal</option><option value="pilot">pilot</option><option value="beta">beta</option><option value="general">general</option></select></label><label className="block"><span className="text-sm">Notes</span><textarea value={notes} maxLength={500} onChange={(e) => setNotes(e.target.value)} className="mt-1 w-full rounded border p-2" /></label>{saveError ? <p className="text-sm text-red-700">{saveError}</p> : null}<div className="flex gap-2"><Button variant="primary" onClick={save} disabled={saving}>{saving ? 'Saving...' : 'Save'}</Button><Button variant="secondary" onClick={() => setEditing(null)} disabled={saving}>Cancel</Button></div></div></Card> : null}</div></SuperAdminLayout>;
};

export default SuperadminFeatureFlagsPage;
