process.env.NODE_ENV = 'production';
process.env.PORT = '5000';
process.env.MONGO_URI = 'mongodb://127.0.0.1:27017/test';
process.env.REDIS_URL = 'redis://127.0.0.1:6379';
process.env.JWT_SECRET = 'security-validation-secret-alpha-bravo-charlie-delta-echo-foxtrot-golf';
process.env.JWT_PASSWORD_SETUP_SECRET = 'account-setup-secret-alpha-bravo-charlie-delta-echo-foxtrot-golf';
process.env.SUPERADMIN_PASSWORD_HASH = '$2b$10$wioLOkqqceK.iu9MZavNOua7yV2AzOpqlR4fuMWHf2.YeYpV4mEFC';
process.env.SUPERADMIN_XID = 'X000001';
process.env.SUPERADMIN_EMAIL = 'superadmin@example.com';
process.env.SUPERADMIN_OBJECT_ID = '000000000000000000000001';
process.env.ENCRYPTION_PROVIDER = 'local';
process.env.MASTER_ENCRYPTION_KEY = ['MDEyMzQ1Njc4OWFiY2RlZj','AxMjM0NTY3ODlhYmNkZWY='].join('');
process.env.METRICS_TOKEN = 'metrics-validation-secret-alpha-bravo-charlie-delta-echo-foxtrot';
process.env.STORAGE_TOKEN_SECRET = 'storage-token-secret-alpha-bravo-charlie-delta-echo-foxtrot-golf';
process.env.UPLOAD_SCAN_STRICT = 'true';
process.env.AUTH_DEBUG_DIAGNOSTICS = 'false';
process.env.DISABLE_GOOGLE_AUTH = 'true';
process.env.ENABLE_EXTERNAL_STORAGE = 'false';
process.env.BREVO_API_KEY = '<dummy-api-key>';
process.env.MAIL_FROM = 'no-reply@example.com';

require('../src/config/validateEnv').validateEnv();
