const DocketStatus = Object.freeze({
  CREATED: 'CREATED',
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  PENDING: 'PENDING',
  PENDED: 'PENDED',
  OPEN: 'OPEN',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  COMPLETED: 'COMPLETED',
  ROUTED: 'ROUTED',
  ROUTED_ASSIGNED: 'ROUTED_ASSIGNED',
  QC_PENDING: 'QC_PENDING',
  QC_FAILED: 'QC_FAILED',
  QC_CORRECTED: 'QC_CORRECTED',
  RESOLVED: 'RESOLVED',
  FILED: 'FILED',
});

module.exports = DocketStatus;
